### PR TITLE
feat: add script tag nonce resolution helper for session management and wmrm

### PR DESCRIPTION
**Pull request by panva**
@matthew-nichols-westtel

please review, this should help with your CSP nonce setup.

### CODE REVIEW

**Comment by matthew-nichols-westtel** [comment]
It looks like scriptNonce will be called and emit a warning if a style-src nonce is set but a script-src nonce is not set

Other than that I don't see anything reading through it

**Comment by panva** [comment]
> It looks like scriptNonce will be called and emit a warning if a style-src nonce is set but a script-src nonce is not set

Is that a big deal? If one's setting CSP nonces it'll set the same one for script and css. I'm willing to look the other way on this one, anything to avoid parsing the csp header.

**Comment by matthew-nichols-westtel** [comment]
As far as I can tell it just means if someone sets a CSS nonce but not a script nonce they'll get a spurious warning, probably not a big deal they can just override scriptNonce to get rid of the warning.

Not a big deal to me. I actually use a different nonce for script and CSS though (don't think it matters here though).

**Comment by panva** [comment]
It doesn’t so long as the function returns the right nonce.

**Comment by matthew-nichols-westtel** [comment]
Fair

**Pull request merged**
