### PR TITLE
5.x RC

### PR DESCRIPTION
**Pull request by panva**
This has been long in development, under wraps. Feel free to comment and make suggestions.

```
npm i panva/node-oidc-provider#5.x
```

# [5.0.0](https://github.com/panva/node-oidc-provider/compare/master...5.x) RC

### Bug Fixes

* change conformIdTokenClaims default value to true ([bccc3af](https://github.com/panva/node-oidc-provider/commit/bccc3af))
* devInteractions also have no-cache headers, doesn't set acr ([a0b123a](https://github.com/panva/node-oidc-provider/commit/a0b123a))
* ensure non-whitelisted JWA algs cannot be used by _jwt client auth ([2fed55d](https://github.com/panva/node-oidc-provider/commit/2fed55d))
* extraClientMetadata.properties keys do not get transformed ([7206832](https://github.com/panva/node-oidc-provider/commit/7206832))
* fixed 500 in client update checking client_secret equality ([56ece4c](https://github.com/panva/node-oidc-provider/commit/56ece4c))
* remove deprecated passing of scope with consent results ([81f7e7a](https://github.com/panva/node-oidc-provider/commit/81f7e7a))
* remove deprecated Session.find upsert behaviour ([5710907](https://github.com/panva/node-oidc-provider/commit/5710907))
* remove deprecated unused exported errors ([f9dcd25](https://github.com/panva/node-oidc-provider/commit/f9dcd25))
* remove got 8 > 9(retries > retry) option re-assign behaviour ([5cda05c](https://github.com/panva/node-oidc-provider/commit/5cda05c))
* secretFactory is now used in client update ([ce9f469](https://github.com/panva/node-oidc-provider/commit/ce9f469))
* validate secret length for client_secret_jwt with no alg specified ([519bb67](https://github.com/panva/node-oidc-provider/commit/519bb67))

### Code Refactoring

* IdToken constructor and `#sign()` method changes ([fc208b9](https://github.com/panva/node-oidc-provider/commit/fc208b9))
* moved thirdPartyCheckUrl under features.sessionManagement ([d4f4a66](https://github.com/panva/node-oidc-provider/commit/d4f4a66))
* renamed deviceCode feature to deviceFlow ([2aa8b6e](https://github.com/panva/node-oidc-provider/commit/2aa8b6e))

### Features

* add self_signed_tls_client_auth client authentication method ([8d0328c](https://github.com/panva/node-oidc-provider/commit/8d0328c))
* add tls_client_auth client authentication method ([644cb5e](https://github.com/panva/node-oidc-provider/commit/644cb5e))
* allow custom mechanisms for handling pairwise identifiers ([85c4c69](https://github.com/panva/node-oidc-provider/commit/85c4c69))
* back and front-channel can be enabled without sessionManagement ([f2fd71c](https://github.com/panva/node-oidc-provider/commit/f2fd71c))
* dynamic token expiration ([2d2619f](https://github.com/panva/node-oidc-provider/commit/2d2619f))
* enable Certificate Bound Access Tokens ([b450de6](https://github.com/panva/node-oidc-provider/commit/b450de6))
* enable explicit whitelist of JWA algorithms ([f3e432c](https://github.com/panva/node-oidc-provider/commit/f3e432c))
* enable token storage and representation format to be dynamic ([cd400dd](https://github.com/panva/node-oidc-provider/commit/cd400dd))
* invalid_token errors now have a detail to aid in debugging or logs ([336c732](https://github.com/panva/node-oidc-provider/commit/336c732))
* JWT Secured Authorization Response Mode for OAuth 2.0 (JARM) ([df16dc2](https://github.com/panva/node-oidc-provider/commit/df16dc2))
* opaque is the default adapter format now ([4ed5756](https://github.com/panva/node-oidc-provider/commit/4ed5756))
* unify audiences helper function signature ([ef2ddc1](https://github.com/panva/node-oidc-provider/commit/ef2ddc1))

### BREAKING CHANGES

* the configuration option `pairwiseSalt` is replaced with `pairwiseIdentifier` async helper function. This allows for different means of generating the pairwise identifier to be implemented, such as the ones mentioned in [Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.8.1)
* Passing `scope` to interaction result's `consent` property is no longer supported
* `cookies.thirdPartyCheckUrl` is now configured with `features.sessionManagement.thirdPartyCheckUrl` instead * `features.deviceCode` is now `features.deviceFlow` and `deviceCodeSuccess` helper function is now `deviceFlowSuccess`
* In order for dynamic token expiration to be able to pass a client instance to the helpers it is now better to pass a `client` property being the client instance to a new token instance rather then a `clientId`. When passing a client the `clientId` will be set automatically.
* the default adapter format is now set to opaque, the legacy "legacy" value is still available for legacy deployments but cannot be combined with the new dynamic format feature option and is considered deprecated and will be removed in the next major release.
* the `default` enabled JWA algorithms have changed. See the new `whitelistedJWA` configuration option to re-enable the ones you need.
* the configuration `unsupported` property is removed, use the configuration `whitelistedJWA` object instead. This isn't a 1:1 renaming of a configuration value, while the `unsupported` option was essentually a blacklist the `whitelistedJWA` as the name suggests is a whitelist.
* the `RSA-OAEP-256` key wrapping algorithm has been removed and is not configurable since it's not supported natively in nodejs.
* IdToken constructor now requires the client instance to be passed in as a second argument. IdToken instance `.sign()` now takes just one argument with the options.
* when a symmetrical endpoint authentication signing alg is not specified the secret will be validated such that it can be used with all available HS bit lengths
* audience helper `token` argument will no longer be a reference to other tokens than the one to which the audiences will be pushed.
* audience helper `scope` argument is no longer available
* `generateTokenId` format method is now a prototype method instead of a class one
* the http request option `retries` will no longer be transformed into `retry`, see `got@^9.0.0` package for the `retry` options
* exported errors `RestrictedGrantType` and `RestrictedResponseType` are no longer available
* Session.find default upsert behaviour is changed to return a new empty session instead
* change conformIdTokenClaims default value to true
* custom client metadata properties will not get transformed between snake_case and camelCase anymore to allow for namespaced metadata properties such as `custom://metadata`

### CODE REVIEW

**Comment by acodercat** [comment]
thanks~

**Comment by acodercat** [comment]
Hope to decouple from KOA and express. just provide middleware.
like this
```js
router.post('/token', oidcProvider.token());
```

**Comment by panva** [comment]
> Hope to decouple from KOA and express. just provide middleware.
> like this
> 
> ```js
> router.post('/token', oidcProvider.token());
> ```

**Comment by panva** [comment]
@acodercat as previously discussed, this is not planned and is not needed, this is a complete implementation, not just middlewares. You can configure the exposed routes and mount the implementation to an existing application using a framework of your choice so long as it supports mounting node.js style (req, res, next) middlewares.

**Pull request merged**
