### PR TITLE
Enable primature end of an interaction via an error result object

### PR DESCRIPTION
**Pull request by KtorZ**
See #167 

I've also added an optional  `error_status_code` field to the error object to be more consistent with other errors created by the provider. When not defined, it default to 400.

### CODE REVIEW

**Comment by panva** [comment]
When is `error_status_code` ever useful? Authorization Errors will always result in a 302 back to the RP unless the problem is with clientid/redirect uri, this includes server_error afaik

**Comment by KtorZ** [comment]
> When is error_status_code ever useful?

Well, I didn't dive much into what `ctx.throw(..)` does, so I thought of keeping the same error format while giving the ability to specify your own error code. I'll simply default to `400` all the time if it's actually not even used.

**Comment by panva** [comment]
If i may, to keep it simple, don't allow the change of the code, always create an error with statusCode 400 and therefore expose true.

The responsible error handler is in lib/shared/authorization_error_handler.js

**Comment by KtorZ** [comment]
done :+1:

**Pull request merged**
