### PR TITLE
chore: upgrade the `got`-dependency

### PR DESCRIPTION
**Pull request by weyert**
Upgraded the `got`-dependency to the same version that is being used by sibling package `node-openid-client`

### CODE REVIEW

**Comment by panva** [comment]
9.6.0 is locked in for v6.x. Can't do much about it, upgrading got would be a breaking change. v7.x coming eventually is going to sport the latest got.

**Comment by weyert** [comment]
Oh okay, then I will keep using v3.x of `openid-client` until v7 :)

**Comment by panva** [comment]
I don't get why. The modules are independent.

**Comment by weyert** [comment]
Yeah, I understand, I will raise a ticket in `openid-client` about it

**Comment by panva** [comment]
If its about conflicting types from @types and the bundled one from updated got, that's a TS deficiency i cannot solve for you.

**Pull request closed without merging**
