### PR TITLE
example: add prisma adapter

### PR DESCRIPTION
**Pull request by Mostafatalaat770**
Add a fully typed Prisma adapter with a reference to an example with the oidc-provider consuming it.

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Thank you! I think the example repo is still private https://github.com/Mostafatalaat770/node-oidc-provider-prisma-adapter

**Comment by Mostafatalaat770** [comment]
> Thank you! I think the example repo is still private https://github.com/Mostafatalaat770/node-oidc-provider-prisma-adapter

Thanks for pointing out that! I totally forgot to make it public

**Comment by amydevs** [comment]
thank you for this! was about to write my own and thought to search through the pull requests

**Comment by Mostafatalaat770** [comment]
> thank you for this! was about to write my own and thought to search through the pull requests

you're welcome! glad I could help.

**Comment by pi0neerpat** [comment]
I used your adapter to create one here https://github.com/UseKeyp/oauth2-server-redwood/blob/d9c00bfdbbe1c18e684aa09343ee27a6e26701bc/api/db/schema.prisma#L53. I have it working now in my Redwood app. I'm currently in the process of adding dynamic client generation.

If you're free, I'd love to hear your input on why you made this schema decisions

```graphql
model Oidc {
   id         String    @id
   type       Int 
   @@unique([id, type])
   @@map("oidc_model")
}

# Instead of 

model Oidc {
   id        String    @default(cuid())
   type       Int
   @@id([id, type])
}
```

**Comment by Mostafatalaat770** [comment]
@pi0neerpat thanks for your feedback! you are right, your suggestion makes more sense, and both will work as intended, I didn't have anything in mind when deciding the schema, but yea I would change it in the future to have the composite key.

**Pull request merged**
