### PR TITLE
Added new configuration property to allow unsafe redirect uris

### PR DESCRIPTION
**Pull request by kay-schecker**
In our project we use your oidc provider as internal test server. For that it would be very useful to allow unsafe redirect_uris, because we want to use localhost and http for local development.
Please see the updated configuration.md for more details.

### CODE REVIEW

**Comment by kay-schecker** [comment]
One of the three builds has failed, but it seems not to be related to my changes?

**Comment by panva** [comment]
Hello @kay-schecker, while I understand the use case and already received these kinds of requests in the past, it is not a feature i wish to offer, not with an env variable, neither with a configuration setting and for sure not as part of recognized client metadata. I'm afraid you'll have to work off a fork or find a another solution. Thank you for understanding, ignoring the specs and allowing this for dev environment will only lead to devs forgetting these options are in place and end up with vulnerable client setups

**Comment by kay-schecker** [comment]
Hi @panva, thanks for your fast reply. I clearly understand your reasoning, but isn't there any other way besides the fork, because this will potentially end in a nightmare of forks, if other developers need the same feature. It would be great to have plugin support for the oidc-provider, so developers can add functionality like this easily.


Regarding your suggestion to use TLS certificates on our dev-servers:

We work with [angular-cli](https://github.com/angular/angular-cli) and start a server on the developer machine itself. This server isn't protected by TLS by default. Furthermore the application is served on 0.0.0.0 / localhost then. That means that we'll run always into the same issue, when we start a new [angular-cli](https://github.com/angular/angular-cli) project. Unfortunately, Angular also has a [bug ](https://github.com/angular/angular-cli/issues/5826) at the moment, so we can't start with TLS at all. But i know this doesn't matter for the oidc-provider. I'm just looking for a solution to my problem.

**Comment by panva** [comment]
I really don't want a feature like this in the code and documentation. I can see the following, and let me know if it works for you.

The `Client` constructor that's returned uses a provider specific `Schema`, this Schema may be assigned to the Client as a class property. Through that you could simply overload the `redirectUris()` schema method to not do any validations. This is hopefully destructive enough that noone will actually use aside of test environments.

**Comment by kay-schecker** [comment]
Thanks a lot i'll give it a try and let you know :-)

**Comment by kay-schecker** [comment]
Yeah, it's working well 👍 Do you plan a new release or a snapshot to publish this change?

**Comment by panva** [comment]
Probably next week, until then just use master.

**Pull request closed without merging**
