### PR TITLE
Feature: allow arrow-function & class-methods as adapter factory

### PR DESCRIPTION
**Pull request by talentumtuum**
Hi!
Now when implementing the "AdapterFactory" type from the package https://www.npmjs.com/package/@types/oidc-provider
a situation can happen where the types are correct, but at runtime we get an error.

I found a mention of this problem here https://github.com/panva/node-oidc-provider/pull/776#issuecomment-714742339

With this PR I add the ability to use arrow-functions and class methods as a factory and at the same time fix the non-obvious behavior when writing code in typescript

### CODE REVIEW

**Comment by co1dmoon** [comment]
like

**Comment by talentumtuum** [comment]
@panva Ready for review

**Comment by talentumtuum** [comment]
@panva I'll take care of this problem in my spare time, I think I'll be back with a solution in 1-3 days, maybe today. Okay?

**Comment by panva** [comment]
Thank you, for sure, come back to the problem any time. FWIW it might be as simple as updating `base_model.js` where the adapters get currently instantiated.

**Comment by talentumtuum** [comment]
@panva Thanks, Thank you for your quick assistance

**Comment by panva** [comment]
Thank you for the PR!

**Pull request merged**
