### PR TITLE
feat: support passing a function for cookies names configuration

### PR DESCRIPTION
**Pull request by JonnyBGod**
@panva Let me know if you agree with this functionality.

It is passing all existing tests but I did not add any new tests for the new behavior. Will add tests if you agree with this PR.

### CODE REVIEW

**Comment by JonnyBGod** [comment]
I am using this to enable Multi Tenancy but it could also be helpful for other use cases.

**Comment by panva** [comment]
Referring back to https://github.com/panva/node-oidc-provider/discussions/916#discussioncomment-409641

> I agree this is helpful in some scenarios but i have doubts about this being the way to go. Seeing the different places you need to pull the client reference from in your code assures me of it.

> I can work from my fork for the time being not to be stuck, it would just give some comfort if we know that you are willing to consider solving this use case in the foreseeable future, so we don't invest in something the ultimately will not be supported.

I would love to have something like this to solve your needs as well as #1065, #1054, and possibly others but this is simply not it, it does not strike me as something that ticks all the boxes when it comes interplay with the rest of the features.

What I have in mind is to offer a full fledged concurrent session support with possibility to offer account chooser, etc. That needs more than just this. If there's need for it and your companies are willing to sponsor the development - drop me a note in my email inbox. Until then it has to wait until I have the time, energy and motivation to design and develop it.

**Comment by JonnyBGod** [comment]
This is not to solve Multi Tenancy per say just a simple improvement to enable you to dynamically set the session names simple enough to maintain.
Even though it is not the best possible solution for multi tenancy it works and it is better than having nothing.

I have been inquired from other users about multi tenancy and how I solved it. Also seen at least a few other users inquiring about it in here as well. So it seams there is some need for it.

But again, this particular PR is quite simple a generic feature that does not add any more complexity, if you look to the changes is really quite a simple change.

And even if we need to wait for a full fledged system, having some alternative working version for now and based on such a small change to the library It seams reasonable to me.

My company I believe is sponsoring you check Fullcube.

**Comment by JonnyBGod** [comment]
For reference:
https://github.com/panva/node-oidc-provider/issues/1047
https://github.com/panva/node-oidc-provider/discussions/1054
https://github.com/panva/node-oidc-provider/discussions/1037

These are all issues and discussion asking about multi tenancy aked by others.

**Comment by panva** [comment]
> And even if we need to wait for a full fledged system, having some alternative working version for now and based on such a small change to the library It seams reasonable to me.

If not used for "multi tenancy" (it means to a lot of different things to a lot of people) I don't actually see use for this, hence as already said before this does not cover the feature set I would have in mind - one that starts with concurrent sessions, scoping sessions' applicability, allowing session selection prompts, ... you see where I'm going at?

> My company I believe is sponsoring you check Fullcube.

A brief sponsorship (it was cancelled after 3 weeks) is not the same as funding feature work that one needs for their deployment. It also does not imply that feature work done without any collaboration in the first place would be simply be accepted.

**Comment by JonnyBGod** [comment]
> - one that starts with concurrent sessions, scoping sessions' applicability, allowing session selection prompts, ... you see where I'm going at?

Concurrent sessions is what I am trying to accomplish and I can do it with this change. The only other thing you need is a way to resolve the clientID and that's it.
Scoping sessions and prompts is also already possible with the current solutions as long as you can have concurrent sessions.
So there is not that much to do and as long as we have this change and hack a bit around resolving the clientId we can accomplish it.

You have the best lib for OICD in node space and I understand you want to focus on the core aspects of the specs, and in reality I don't think you need to maintain and support a full multi tenancy lib as this is mostly used by companies that should have the resources to maintain it.

All I am asking is to unblock the functionality with this small change.

Regarding the sponsorship, I did not know it was canceled. Will check that out. We can also discuss how we can finance your work better as well.

**Comment by MichaelRo** [comment]
Adding to that, this solution is the exact solution we thought about, and probably will use
Can we add this code hidden by a feature?

**Comment by panva** [comment]
Circling back to https://github.com/panva/node-oidc-provider/pull/1066#issuecomment-886099234 please respect my decision not to accept this change. The same PR has already been closed before this one and nothing has changed since.

There will be native support for concurrent sessions, scoping sessions' applicability and account choosing eventually. The "when" depends on either my free time and enthusiasm about the feature (which is low atm) or someone coming in and funding its development.

Over the 6 years and 7 major versions the library has grown considerably. Single-handedly maintaining it, improving it, continuously certifying it, etc is not a trivial task. Adding features needs a bigger picture first approach. Accepting even a small change needs to have interplay with the rest of the features (existing and future ones).

**Comment by JonnyBGod** [comment]
Well with this kind of response it is not easy to break from the "Single-handedly maintaining it" situation, it it?

There are at least 3 developer here that need this and are willing to help. Just repeating the money problem and the lack of time does not solve anything does it?

We proposed a plan that works for the interested parties. Can you share your plan with us, we might be able to help...

You ask us to respect your decision but I don't see a lot of respect for our needs and contributions when the repeated response is "No because I don't want it and have a plan...".

Help us understand your plan and I will help develop it.
Its your library and you decide, but don't ask me to respect your decision when you give me no respectable answers.

Also the previous PR for version 6 was too hacky and at the time I understood why you did not want to include it. But now with version 7 the needed changes are very minor and do not create any overhead. That is why I proposed a PR again.
This time I do not understand why you don't consider it.

Again, tell me how you see this being done and I will do it.

**Comment by panva** [comment]
> Well with this kind of response it is not easy to break from the "Single-handedly maintaining it" situation, it it?

It was not a complaint, but a statement. I'm not attempting to break from it.

Now, just now, did you ask the first time "how do I want it?", before then it was only "can we please have this thing?".

> Help us understand your plan

I will unblock your needs to drive the cookie name value dynamically through an OIDCContext prototype method. It will maybe be only done for the `'session'` cookie, but you're then free to overload it and do whatever whacky and hacky resolution that you have in this proposed helper today. It will not be part of the public documented API and whenever a full blown solution is there it will most likely be completely decommissioned. 

I welcome those who need the features described (concurrent sessions, scoping sessions' applicability, allowing session selection prompts) to sponsor the library and get a chance to be a part of the design process for a native solution then.

**Comment by JonnyBGod** [comment]
Ok fair enough.

We just need the session cookies for this.

**Comment by xelinorg** [comment]
Usually I do not like to solve problems for others when I have not solved my own. When I settle and I have decided what is the plan for solving the problem,  I take ownership and go ahead to support my decision and if there is delegation or if this could effect others  I always think twice and I am not an easy go... 

@JonnyBGod you could fork and take the responsibility of your code and what you have done to solve the multi-tenancy problem or any other problem your solution addresses. If you offload here then all of us who are using the library could have issues and is not very sure that you will be here to support... @panva has created this and is doing the support for some years now so I expect him to be around.

**Comment by panva** [comment]
@JonnyBGod see the `dynamic-session-cookie-name` branch and tell me if it works for you.

```js
const provider = new Provider(...);
const fn = function () {
  const { ctx } = this;
  return 'foobar';
};
Object.defineProperty(provider.OIDCContext.prototype, 'sessionCookieName', {
  get: fn,
});
```

**Comment by JonnyBGod** [comment]
@panva something like this can work but would need to support returning a promise or having a call back as we need to make a request to the database.

**Comment by panva** [comment]
What do you need to fetch from the database that isn't otherwise available?

**Comment by JonnyBGod** [comment]
We are correlating oidcClients with "organizations" and currenlty setting the session cookie names with the "organization" id.

Now that I think about it I think we can just use the client id instead and resolve Organization later.

There is still a use case that I am not sure it is still needed since version 7 though.

This is the way we try to resolve the clientId:
```
async getClientId(ctx): Promise<string> {
    let clientId = ctx.oidc?.client?.clientId || ctx.oidc.client?.id

    if (!clientId && ctx.request.query['client_id']) {
      clientId = ctx.request.query['client_id'] as string
    }

    if (!clientId && ctx.request.headers?.referer) {
      const query = new URL(ctx.request.headers.referer).searchParams
      clientId = query['client_id'] as string
    }

    if (!clientId && ctx.request.query['id_token_hint']) {
      clientId = decode(ctx.request.query['id_token_hint'] as string)?.payload?.aud
    }

    if (!clientId && ctx.oidc) {
      const id = ctx.oidc.cookies.get('_resume') || ctx.oidc.cookies.get('_interaction')

      if (id) {
        const {
          payload: { params },
        }: // eslint-disable-next-line @typescript-eslint/no-explicit-any
        any = await this.collection.findOne({ _id: id })

        if (!params?.client_id) {
          throw new Error('interaction session id cookie not found')
        }

        clientId = params.client_id
      }
    }

    return clientId
}
```

At the time we needed all these steps to support all the possible flows. I did not yet checked the need for these since upgrading to version 7 though. If we can live without the last snerario there, we would not need async support anymore.

**Comment by panva** [comment]
@JonnyBGod So, can you work with just client_id synchronously? Or keep the overall mapping between client_id and organization in process cached and prepared to be used synchronously? Is that an unsolvable problem if this remains sync as it is today?

**Comment by JonnyBGod** [comment]
While not ideal I could live with a solutions such as a in memory cache for clientId -> organizationId.

However I have yet to find a solution when we need to resolve the clientId from a resume or interaction cookie. In this case we still need to grab the cookie and get it from the database.

If you see some options here I would be happy to try it. Otherwise I think we need the async functionality.

**Comment by JonnyBGod** [comment]
Also happy to ear if you have any other possible solutions for the session naming.
We think the main requisites are to enable parallel sessions between clients while disallowing multiple session for the same client or in our case for the same organization.

**Comment by panva** [comment]
I see what you mean, I would suggest you to store the organization or client in your own cookie to read during interaction resume. You can do so e.g. in the `interactions.url` helper through [`ctx.cookies.set(name, value, [options])
`](https://koajs.com/#ctx-cookies-set-name-value-options-).

**Comment by JonnyBGod** [comment]
Ok seams like a solution.
Will have to try it out for all use cases.
Give me a couple of days to try this approach.

**Comment by JonnyBGod** [comment]
I believe the same problem with resolving the Client Id persists.

The new cookie would need to correlate Client Id with Organization ID we would still need to resolve the Client Id on "sessionCookieName" call.

It's not difficult to solve the Organization Id problem, the whole issue from the beginning is related to resolving Client ID for all possible interaction flows.

**Comment by panva** [comment]
The mapping is something you gotta figure out and keep available.

When you're on `ctx.oidc.route === 'authorize'` the client id is resolvable synchronously. When interactions are required you set a cookie for yourself in `interactions.url`.

When you're on `'resume'` you read that cookie and use that.

I don't see an issue. You may as well have your client identifiers contain the organization identifier.

**Comment by panva** [comment]
You can also pass the client id or organization identifier along to your resume route as a query argument.

**Comment by JonnyBGod** [comment]
I got to the point where I create a new cookie as you proposed with name set to "org_INTERACTION_UID", then on "sessionCookieName" I can resolved the cookie from the interaction uid that I grab from the context params.

This works fine during most interactions and I managed to complete the login flow.

The problem I got then was when login in again with an existing session.
In this case the context does not have an interaction uid meaning that I would need to fall back to a client id based session cookie name.

And for that I need to use this async function:
```typescript

async function getClientId(ctx, collection: Collection<AdapterPayload>): Promise<string> {
  let clientId = ctx.oidc?.client?.clientId || ctx.oidc.client?.id

  if (!clientId && ctx.request.query['client_id']) {
    clientId = ctx.request.query['client_id'] as string
  }

  if (!clientId && ctx.request.headers?.referer) {
    const query = new URL(ctx.request.headers.referer).searchParams
    clientId = query['client_id'] as string
  }

  if (!clientId && ctx.request.query['id_token_hint']) {
    clientId = decode(ctx.request.query['id_token_hint'] as string)?.payload?.aud
  }

  if (!clientId && ctx.oidc) {
    const id = ctx.oidc.cookies.get('_resume') || ctx.oidc.cookies.get('_interaction')

    if (id) {
      const {
        payload: { params },
      }: // eslint-disable-next-line @typescript-eslint/no-explicit-any
      any = await collection.findOne({ _id: id })

      if (!params?.client_id) {
        throw new Error('interaction session id cookie not found')
      }

      clientId = params.client_id
    }
  }

  return clientId
}
```

Any other ideas?

**Comment by panva** [comment]
I don't understand. Assuming client id can be resolved to a bucket.

- at /authorize I can always get the bucket because you always have a client_id
- when interactions are required interactions.url is called and you store the bucket
- at the "resume" endpoint I can always get the bucket because it is in the cookie

Nevertheless

- you can make your client identifiers structured to always have the bucket in its value
- you can pass the bucket to resume without a cookie using a query string parameter

**Comment by JonnyBGod** [comment]
I believe it is working.

```typescript
interactions: {
  ...configuration.interactions,
  url: async (ctx: KoaContextWithOIDC, interaction): Promise<string> => {
    const clientId = getClientId(ctx)

    if (clientId) {
      const iv = randomBytes(16)
      const cipher = createCipheriv(algorithm, secretKey, iv)

      ctx.cookies.set(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        `_client_${interaction.uid || (ctx.oidc as any)?.uid}`,
        `${Buffer.concat([cipher.update(clientId.toString()), cipher.final()]).toString('hex')}:${iv.toString(
          'hex'
        )}`,
        {
          maxAge: 3600 * 1000, // 1 hour in milliseconds
          overwrite: true,
          signed: true,
        }
      )
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return `/interaction/${interaction.uid || (ctx.oidc as any)?.uid}`
  },
},
```

```typescript
this.provider.on('interaction.ended', (ctx: KoaContextWithOIDC) => {
  if (ctx.params.uid) {
    ctx.cookies.set(`_client_${ctx.params.uid}`, null)
    ctx.cookies.set(`_client_${ctx.params.uid}.sig`, null)
  }
})

Object.defineProperty(this.provider.OIDCContext.prototype, 'sessionCookieName', {
  get: function () {
    const { ctx } = this
    let clientId = ctx.oidc?.client?._id

    if (!clientId) {
      clientId = getClientId(ctx)
    }

    if (clientId) {
      return `_session_${createHash('md5').update(clientId.toString()).digest('hex')}`
    }

    return null
  },
})
```

```typescript
function getClientId(ctx): string {
  let clientId = ctx.oidc?.client?.clientId || ctx.oidc.client?.id

  if (!clientId && ctx.request.query['client_id']) {
    clientId = ctx.request.query['client_id'] as string
  }

  if (!clientId && ctx.request.headers?.referer) {
    const query = new URL(ctx.request.headers.referer).searchParams
    clientId = query['client_id'] as string
  }

  if (!clientId && ctx.request.query['id_token_hint']) {
    clientId = decode(ctx.request.query['id_token_hint'] as string)?.payload?.aud
  }

  if (!clientId && ctx.params.uid) {
    const cookies = getCookiesAsCollection(ctx.request.header.cookie)
    // eslint-disable-next-line no-prototype-builtins
    if (cookies.hasOwnProperty(`_client_${ctx.params.uid}`)) {
      const [hash, iv] = cookies[`_client_${ctx.params.uid}`].split(':')
      const decipher = createDecipheriv(algorithm, secretKey, Buffer.from(iv, 'hex'))
      clientId = Buffer.concat([decipher.update(Buffer.from(hash, 'hex')), decipher.final()]).toString()
      ctx.cookies.set(`_client_${ctx.params.uid}`, null)
      ctx.cookies.set(`_client_${ctx.params.uid}.sig`, null)
    }
  }

  return clientId
}
```

Will keep testing but untill now every flow worked including "recover account/reset password", "third party passport login", "email verification".

Quick question, do you see any better method to clear the cookies when interaction cookies are cleared?

**Comment by JonnyBGod** [comment]
@panva Everything is working fine for a week now with this new feature.
Will you publish it or keep it on a separate branch?

**Pull request closed without merging**
