### PR TITLE
docs: fix extraClientMetadata typo

### PR DESCRIPTION
**Pull request by Mostafatalaat770**

### CODE REVIEW

**Comment by panva** [comment]
👋 this has to be changed in the source file, lib/helpers/defaults.js

**Comment by Mostafatalaat770** [comment]
should I open a new pull request?

**Comment by panva** [comment]
Nop, just amend this one ;)

**Comment by panva** [comment]
Would you please only submit relevant changes? You have accidentally submitted a completely reformatted file.

**Comment by Mostafatalaat770** [comment]
Yea, auto-saving kicked unintentionally 😅

**Pull request merged**
