### PR TITLE
New Adapter, fix imports and JSdoc

### PR DESCRIPTION
**Pull request by cymarechal**

### CODE REVIEW

**Comment by cymarechal** [comment]
[Job #164.1](https://travis-ci.com/panva/node-oidc-provider/jobs/133611697) timed out on `npm install`... any idea?

**Comment by panva** [comment]
Hi @cymarechal and thank you!

Similar to #244, could you provide an "author" comment on top with your username and preferably way of contacting you when others have a question/issues related to your adapter example?

**Comment by cymarechal** [comment]
Done!

**Comment by panva** [comment]
Perfect!

**Comment by cymarechal** [comment]
Thank you @panva for accepting my first ever contribution

**Pull request merged**
